USEPA/EnviroAtlas_JSApp

- config.json
- widgets/AddData/css/style.css
- widgets/AddData/nls/strings.js
- widgets/AddData/search/AddFromUrlPane.js
- widgets/AddData/search/ItemCard.js
- widgets/AddData/search/LayerLoader.js
- widgets/AddData/search/ResultsPane.js
- widgets/AddData/search/templates/AddFromUrlPane.html
- widgets/DrawerAddDataTools/config.json
- widgets/LayerList/LayerListView.js
Not completely done yet, but worth deploying for now.
> #64 implement add data 2.5 widget

- themes/TabTheme/panels/TabPanel/TabWidgetFrame.html
- themes/TabTheme/panels/TabPanel/style.css
- themes/TabTheme/widgets/SidebarController/Widget.js
- themes/TabTheme/widgets/SidebarController/css/style.css
Jeremy pushed changes for the sidebar
> sidepanel apperance

- scripts/ConvertEsriCachetoXYZ.py
> Cachescripts

- widgets/LayerList/LayerListView.js
- widgets/LayerList/css/style.css
- widgets/LocalLayer/Widget.js
- widgets/PeopleAndBuildSpaces/Widget.js
- widgets/SimpleSearchFilter/Widget.js
- widgets/SimpleSearchFilter/css/style.css
> Layer list style

- widgets/GoogleAnalytics/Widget.js
Quick addition of search term tracking - @brosenbaum go ahead and deploy if you feel comfortable, I think it's pretty low risk and tests out even in IE.
> Advanced google analytics

- widgets/AddWebMapData/Widget.js
Seems to fix most issues with feature layers - leaving outstanding issues with dynamic map services and layers saved as separate content items.
> working on featured collections odd behaviors.

- widgets/Demo/config.json
Tour stop nodes were off.  Fixed
> fix demo steps

- widgets/Demo/help/templates/help_AddData1.html
- widgets/Demo/help/templates/help_Demographic1.html
- widgets/Demo/help/templates/help_Demographic2.html
- widgets/Demo/help/templates/help_DrawerMapping1.html
- widgets/Demo/help/templates/help_DrawerMapping2.html
- widgets/Demo/help/templates/help_ECAT1.html
- widgets/Demo/help/templates/help_ECAT2.html
- widgets/Demo/help/templates/help_Elevation1.html
- widgets/Demo/help/templates/help_Elevation2.html
- widgets/Demo/help/templates/help_EndPage.html
- widgets/Demo/help/templates/help_EnviroAtlasDataSearch1.html
- widgets/Demo/help/templates/help_FeaturedCollections1.html
- widgets/Demo/help/templates/help_HucNavigation1.html
- widgets/Demo/help/templates/help_HucNavigation2.html
- widgets/Demo/help/templates/help_Raindrop1.html
- widgets/Demo/help/templates/help_Raindrop2.html
- widgets/Demo/help/templates/help_SelectCommunity1.html
- widgets/Demo/help/templates/help_TimesSeries1.html
New updates to help HTMLs for the tour widgets.
> Additions and updates to help HTMLs for in-context widgets.

- config.json
- widgets/Demo/help/templates/help_AddData2.html
- widgets/Demo/help/templates/help_AttributeTable2.html
- widgets/Demo/help/templates/help_Demographic2.html
- widgets/Demo/help/templates/help_DrawMeasure2.html
- widgets/Demo/help/templates/help_DrawerMapping1.html
- widgets/Demo/help/templates/help_DrawerMapping2.html
- widgets/Demo/help/templates/help_DynamicSymbology2.html
- widgets/Demo/help/templates/help_ECAT2.html
- widgets/Demo/help/templates/help_Elevation2.html
- widgets/Demo/help/templates/help_EndPage.html
- widgets/Demo/help/templates/help_EnhancedBookmarks2.html
- widgets/Demo/help/templates/help_EnviroAtlasDataSearch2.html
- widgets/Demo/help/templates/help_FeaturedCollections2.html
- widgets/Demo/help/templates/help_HucNavigation2.html
- widgets/Demo/help/templates/help_LayerList2.html
- widgets/Demo/help/templates/help_Print2.html
- widgets/Demo/help/templates/help_Raindrop2.html
- widgets/Demo/help/templates/help_SelectByTopic2.html
- widgets/Demo/help/templates/help_SelectCommunity2.html
- widgets/Demo/help/templates/help_TimesSeries2.html
- widgets/Demo/help/templates/help_standalone.html
So the main problem with this fix is that when the images are sourced to the root, the paths need to be updated when moving to production. Need to discuss.
> Create standalone help page, adjust image paths.

- config.json
- widgets/GriddedMapTool/Widget.html
- widgets/GriddedMapTool/Widget.js
- widgets/GriddedMapTool/css/style.css
- widgets/GriddedMapTool/nls/strings.js
multiple updates to UI and functionality of Gridded Analysis Tool
> Jb grid tool

- index.html
- widgets/GriddedMapTool/Widget.html
- widgets/GriddedMapTool/Widget.js
- widgets/GriddedMapTool/css/style.css
- widgets/GriddedMapTool/nls/strings.js
Large update to Gridded Analysis Tool.
> updated gridded analysis; removed highcarts; added d3

- widgets/Demo/help/templates/help_ECAT1.html
- widgets/Demo/help/templates/help_ECAT2.html
- widgets/ECAT/Widget.html
Decommission ECAT widget - replace widget UI, tour and help documentation with message
> Decommission ECAT widget

- widgets/LayerList/LayerListView.js
States, counties, and census block groups layers not displaying properly
> States, counties, and census block groups layers not displaying properly

- config.json
- widgets/GriddedMapTool/Widget.html
- widgets/GriddedMapTool/css/style.css
Update SMA panel size. Make errors visible once selections are made. Space "Clear Selection" buttons evenly and improve color contrast.
> Update SMA panel css

- config.json
Remove ECAT from prod app since it has different widgets than the staging app.
> Remove ECAT from config

- widgets/GriddedMapTool/Widget.html
- widgets/GriddedMapTool/Widget.js
This is just to show you the current difference in repos, please do not merge.
> diff from staging to prod repo

- widgets/Drawer/config.json
Correct HUC Navigation Tool name in the drawer config
> Correct HUC Navigation Tool name in the drawer config

- jimu.js/main.js
- widgets/CompareMyArea/configLocal.js
- widgets/DemographicLayers/Widget.html
- widgets/DemographicLayers/Widget.js
- widgets/DemographicLayers/configLocal.js
bugfix for broken demog layers
> Bugfix prod demog sublayers layerlist

- widgets/CompareMyArea/configLocal.js
- widgets/DemographicLayers/Widget.html
- widgets/DemographicLayers/Widget.js
- widgets/DemographicLayers/configLocal.js
bugfix for broken demog layers
> Update ejscreen service to 2021

- widgets/Raindrop/Widget.js
Lines 213-235 have functional changes. Also, format code for readability.
> Bugfix prod raindrop point indexing call

- widgets/AddData/config.json
- widgets/AddData/search/SortOptions.js
- widgets/AddData/search/templates/SortOptions.html
Update curated content configuration. Change title to "EnviroAtlas Picks" and filter to EA group. Default sorting by Title.
> Update Add Date configurations.

- config.json
- widgets/Raindrop/Widget.html
Move warning message to top of widget pane. Change warning message text.
> Move warning message to top of widget pane. Change warning message text.
